"""Identity & tenancy tables — the Phase 1 first slice (docs 03 §2, 06 §5).

Five tables: ``organizations``, ``actors``, ``member_auth``,
``memberships``, ``sessions``. Universal row invariants (doc 06 §4) apply:
UUIDv7 ``id`` primary keys generated by ``platform/ids`` (M6), immutable
indexed ``organization_id`` on every tenant-bearing table (C2/INV-ROW-1), and
``created_at`` server defaults.

Same-org referential integrity (INV-TENANT-4, doc 06 INV-TABLE-1): FKs to
tenant-bearing rows are *composite* ``(organization_id, <id>)`` references so
a cross-org reference cannot be committed. The one deliberate exception is
``memberships.auth_identity_id`` — doc 05 §2 allows an identity to hold
memberships in multiple organizations, so that FK is intentionally
single-column.

Immutability of IMM columns and Row-Level Security are enforced in the
database by revision 0002 (triggers + policies, doc 06 §4 / doc 05 §3.2);
they are deliberately not represented in this metadata because autogenerate
does not manage them.

State-value CHECK constraints cover only the sets doc 03 fixes in the schema
(org/session/identity states, membership roles, trust tiers, lifecycle
phases, health). ``actor_type``/``actor_subtype`` and the actor lifecycle
``state`` are Type-Registry-validated data (doc 03 §8) and get no CHECK —
hardcoding them would recreate H3.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import (
    CheckConstraint,
    ForeignKey,
    ForeignKeyConstraint,
    Index,
    Integer,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, TIMESTAMP, UUID
from sqlalchemy.orm import Mapped, mapped_column

from xiosync.persistence.models.base import Base
from xiosync.platform.ids import new_id

_timestamptz = TIMESTAMP(timezone=True)


class Organization(Base):
    """The tenant boundary; root of all isolation (doc 03 §2.1)."""

    __tablename__ = "organizations"
    __table_args__ = (
        UniqueConstraint("slug"),
        # Same-org composite-FK anchor: (id, id) is trivially unique via the
        # PK, but child tables reference (organization_id, id) pairs on the
        # *tenant-bearing* tables below, not on organizations itself.
        CheckConstraint(
            "state IN ('active', 'suspended', 'archived')",
            name="state_allowed",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=new_id)
    slug: Mapped[str] = mapped_column(Text, nullable=False)  # IMM (trigger, rev 0002)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    state: Mapped[str] = mapped_column(Text, nullable=False)
    # Gap D-2: user-declared external provider registry (storage, vector store,
    # database, etc.). Platform stores the reference — never reads/writes the
    # actual data. Structure is org-defined: e.g.
    # {"artifact_storage": {"provider": "r2", "bucket": "..."}, ...}
    external_providers: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    # Gap M-1: per-org resource quotas (max_workers, max_queued_tasks,
    # max_concurrent_runs, max_daily_events). Empty = unlimited.
    resource_quotas: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    created_at: Mapped[datetime] = mapped_column(
        _timestamptz, nullable=False, server_default=text("now()")
    )  # IMM
    updated_at: Mapped[datetime | None] = mapped_column(_timestamptz)


class Actor(Base):
    """Any participating entity: human, AI, or compute (doc 03 §2.3)."""

    __tablename__ = "actors"
    __table_args__ = (
        # Anchor for same-org composite FKs from this and other tables.
        UniqueConstraint("organization_id", "id"),
        ForeignKeyConstraint(
            ["organization_id", "parent_id"],
            ["actors.organization_id", "actors.id"],
            name="fk_actors_parent_same_org",
        ),  # INV-ACTOR-2: cross-org parenting is structurally impossible
        ForeignKeyConstraint(
            ["organization_id", "created_by"],
            ["actors.organization_id", "actors.id"],
            name="fk_actors_created_by_same_org",
        ),
        CheckConstraint(
            "lifecycle_phase IN ('pre_birth', 'birth', 'operational', 'end_of_life')",
            name="lifecycle_phase_allowed",
        ),
        CheckConstraint(
            "trust_tier IN ('newcomer', 'contributor', 'trusted', 'core', 'admin')",
            name="trust_tier_allowed",
        ),
        CheckConstraint(
            "health_status IN ('healthy', 'degraded', 'offline', 'unknown')",
            name="health_status_allowed",
        ),
        Index("ix_actors_org_type_state", "organization_id", "actor_type", "state"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=new_id)
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organizations.id"), nullable=False, index=True
    )  # IMM (INV-ACTOR-1)
    actor_type: Mapped[str] = mapped_column(Text, nullable=False)  # registry-validated
    actor_subtype: Mapped[str | None] = mapped_column(Text)  # registry-validated
    role: Mapped[str | None] = mapped_column(Text)  # scoped role reference (doc 03 §5)
    alias: Mapped[str | None] = mapped_column(Text)
    parent_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    state: Mapped[str] = mapped_column(Text, nullable=False)  # registry-validated (doc 03 §4.1)
    lifecycle_phase: Mapped[str] = mapped_column(Text, nullable=False)
    trust_tier: Mapped[str] = mapped_column(Text, nullable=False)
    config: Mapped[dict[str, Any] | None] = mapped_column(JSONB)  # IMM (init args)
    runtime_state: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    health_status: Mapped[str] = mapped_column(Text, nullable=False)
    last_heartbeat: Mapped[datetime | None] = mapped_column(_timestamptz)
    created_by: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    created_at: Mapped[datetime] = mapped_column(
        _timestamptz, nullable=False, server_default=text("now()")
    )  # IMM
    updated_at: Mapped[datetime | None] = mapped_column(_timestamptz)


class MemberAuth(Base):
    """An authentication principal — login credentials (doc 03 §2.2)."""

    __tablename__ = "member_auth"
    __table_args__ = (
        # Anchor for same-org composite FKs (sessions).
        UniqueConstraint("organization_id", "id"),
        # Email unique within organization; service layer normalizes case.
        UniqueConstraint("organization_id", "email"),
        # INV-AUTH-1: 1:1 with a HumanActor.
        UniqueConstraint("human_actor_id"),
        ForeignKeyConstraint(
            ["organization_id", "human_actor_id"],
            ["actors.organization_id", "actors.id"],
            name="fk_member_auth_human_actor_same_org",
        ),
        CheckConstraint(
            "state IN ('active', 'locked', 'disabled')",
            name="state_allowed",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=new_id)
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organizations.id"), nullable=False, index=True
    )  # IMM (INV-AUTH-2)
    human_actor_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)  # IMM
    email: Mapped[str] = mapped_column(Text, nullable=False)
    password_hash: Mapped[str] = mapped_column(Text, nullable=False)  # argon2id; never plaintext
    state: Mapped[str] = mapped_column(Text, nullable=False)
    failed_attempts: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    locked_until: Mapped[datetime | None] = mapped_column(_timestamptz)
    created_at: Mapped[datetime] = mapped_column(
        _timestamptz, nullable=False, server_default=text("now()")
    )  # IMM
    updated_at: Mapped[datetime | None] = mapped_column(_timestamptz)


class Membership(Base):
    """An identity's role in one organization (docs 03 §5, 05 §2, 06 §5)."""

    __tablename__ = "memberships"
    __table_args__ = (
        UniqueConstraint("auth_identity_id", "organization_id"),
        CheckConstraint(
            "membership_role IN ('org_owner', 'org_admin', 'org_member', 'org_viewer')",
            name="membership_role_allowed",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=new_id)
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organizations.id"), nullable=False, index=True
    )  # IMM
    # Deliberately single-column: an identity MAY hold memberships in other
    # organizations than its home org (doc 05 §2).
    auth_identity_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("member_auth.id"), nullable=False
    )  # IMM
    membership_role: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        _timestamptz, nullable=False, server_default=text("now()")
    )  # IMM
    updated_at: Mapped[datetime | None] = mapped_column(_timestamptz)


class Session(Base):
    """Server-side, revocable authentication session (doc 03 §2.10; C8)."""

    __tablename__ = "sessions"
    __table_args__ = (
        ForeignKeyConstraint(
            ["organization_id", "auth_identity_id"],
            ["member_auth.organization_id", "member_auth.id"],
            name="fk_sessions_auth_identity_same_org",
        ),
        CheckConstraint(
            "state IN ('active', 'revoked', 'expired')",
            name="state_allowed",
        ),
        # Hot path: revoke-all / validate for one identity (doc 06 §7).
        Index(
            "ix_sessions_auth_identity_active",
            "auth_identity_id",
            postgresql_where=text("state = 'active'"),
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=new_id)
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organizations.id"), nullable=False, index=True
    )  # IMM
    auth_identity_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)  # IMM
    refresh_token_hash: Mapped[str] = mapped_column(Text, nullable=False)
    access_token_jti: Mapped[str | None] = mapped_column(Text)
    state: Mapped[str] = mapped_column(Text, nullable=False)
    expires_at: Mapped[datetime] = mapped_column(_timestamptz, nullable=False)
    last_used_at: Mapped[datetime | None] = mapped_column(_timestamptz)
    revoked_at: Mapped[datetime | None] = mapped_column(_timestamptz)
    created_at: Mapped[datetime] = mapped_column(
        _timestamptz, nullable=False, server_default=text("now()")
    )  # IMM
    updated_at: Mapped[datetime | None] = mapped_column(_timestamptz)
