"""organization_branding

Revision ID: 5c2c0ef8c0d1
Revises: 0025
Create Date: 2026-09-03 16:31:37.127984

Reversibility (INV-MIG-3): reversible unless explicitly documented otherwise
below, with the reason.
"""

from __future__ import annotations

from sqlalchemy.dialects import postgresql
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5c2c0ef8c0d1'
down_revision: str | None = '0026'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_branding',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('theme_mode', sa.String(), server_default='system', nullable=False),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('favicon_url', sa.String(), nullable=True),
    sa.Column('custom_domain', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_branding_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', name=op.f('pk_organization_branding')),
    sa.UniqueConstraint('custom_domain', name=op.f('uq_organization_branding_custom_domain'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_branding')
    # ### end Alembic commands ###
