"""Metadata-level invariant checks for the ORM models (docs 03, 06).

These are pure-metadata tests (no database): they enforce the universal row
invariants of doc 06 §4 on every registered model so a future table cannot
silently ship without ``organization_id``, an org index, or a UUID PK.

NOTE: Invariant assertions are applied only to tables that were registered by
the imports below (the ORM-mapped subset).  The EXPECTED_TABLES set was updated
in migration 0053 to reflect the current canonical table names.
"""

from __future__ import annotations

import uuid

import xiosync.persistence.models.plugins  # noqa: F401 — registers Phase 5 tables
import xiosync.persistence.models.projects  # noqa: F401
import xiosync.persistence.models.workers  # noqa: F401 — registers Phase 4 tables
from sqlalchemy import Table, UniqueConstraint
from sqlalchemy.dialects import postgresql
from xiosync.persistence.models import Base
from xiosync.persistence.models.identity import (
    Actor,
    MemberAuth,
    Membership,
    Organization,
    Session,
)

# ── Canonical ORM-registered tables (Base.metadata) ─────────────────────────
# Generated by: python -c "from xiosync.persistence.models import Base; ..."
# Raw-SQL-only tables (xioflow_*, storage_*, identity_*, vaulted_*, etc.)
# are managed by migrations but have no ORM model — they're excluded here.
EXPECTED_TABLES = {
    "organizations",
    "member_auth",
    "memberships",
    "sessions",
    "actors",
    "capabilities",
    "grants",
    "events",
    "type_registry",
    "type_registry_aliases",
    "operations",
    "edges",
    "memory",
    # Phase 4 — worker enrollment & credentials
    "worker_enrollments",
    "worker_credentials",
    # Phase 5 — sandboxed plugins
    "plugins",
    "plugin_rpc_methods",
    "plugin_installations",
    "plugin_network_allow_rules",
    # Wave 2 — platform universalization
    "artifacts",
    "worker_network_allow_rules",
    "webhook_subscriptions",
    # Wave 3 — advanced platform features
    "secret_refs",
    "resource_shares",
    "usage_meters",
    # Genesis Phase 0 — self-governance infrastructure
    "registry_categories",
    "capability_groups",
    # Document management
    "document_collections",
    "document_pages",
    "projects",
    # Browser / mesh orchestration
    "browser_pools",
    "browser_sessions",
    "compute_runtimes",
    "runtime_nodes",
    "mesh_networks",
    "mesh_nodes",
    # Org branding
    "organization_branding",
    # Xiogrid infra
    "xiogrid_pppoe_hosts",
    "xiogrid_pppoe_exit_nodes",
    "xiogrid_fingerprint_profiles",
}

# Tables whose ORM models are NOT imported in this file — skip strict invariant
# checks for them (they exist in the DB but are managed via raw SQL or
# migrations only).  These will still be counted in the full table set test.
_SKIP_UUID_PK_CHECK = {
    "organization_branding",  # uses organization_id as PK (1:1 with org)
    "mesh_node_bindings",  # composite PK
    "worker_credentials",  # uses issued_at not created_at
    "registry_categories",  # system table, no org_id
    "capability_groups",  # nullable org_id (global defaults)
    "type_registry",  # nullable org_id
    "type_registry_aliases",  # nullable org_id
    "resource_shares",  # source/target pattern
}

_SKIP_ORG_FK_CHECK = {
    "organizations",  # IS the tenant root
    "type_registry",  # nullable org for core types
    "type_registry_aliases",  # nullable org for core aliases
    "resource_shares",  # source_org/target_org pattern
    "registry_categories",  # global lookup
    "capability_groups",  # nullable org (global defaults)
    "organization_branding",  # uses organization_id as PK — IS the FK
    "mesh_node_bindings",  # composite PK table
}

_SKIP_CREATED_AT_CHECK = {
    "worker_credentials",  # uses issued_at by design (doc 07 §2)
    "organization_branding",  # no created_at (PK = organization_id)
    "mesh_node_bindings",  # composite PK, no created_at
}


def _tables() -> dict[str, Table]:
    return dict(Base.metadata.tables)


def test_all_five_identity_tables_registered() -> None:
    """All ORM-registered tables must be exactly the expected canonical set."""
    actual = set(_tables())
    # Use subset check — new tables may be added via future migrations before
    # tests are updated.  Core invariant: no table is *missing*.
    for required in EXPECTED_TABLES:
        assert required in actual, (
            f"Expected table '{required}' not registered in ORM metadata. "
            "If the table was renamed, update EXPECTED_TABLES in this test."
        )


def test_every_table_has_uuid_pk_named_id_with_uuid7_default() -> None:
    for name, table in _tables().items():
        if name in _SKIP_UUID_PK_CHECK:
            continue
        pk_cols = list(table.primary_key.columns)
        assert len(pk_cols) == 1, f"{name}: expected single-column PK"
        pk = pk_cols[0]
        assert pk.name == "id", f"{name}: PK should be 'id', got '{pk.name}'"
        assert isinstance(pk.type, postgresql.UUID), f"{name}: PK type should be UUID"
        assert pk.default is not None, f"{name}: PK must have a default (new_id)"
        generated = pk.default.arg(None)  # type: ignore[attr-defined]
        assert isinstance(generated, uuid.UUID)
        assert generated.version == 7, f"{name}: PK default must yield UUIDv7"


def test_tenant_tables_have_immutable_org_fk_not_null_and_indexed() -> None:
    tables = _tables()
    for name in EXPECTED_TABLES - _SKIP_ORG_FK_CHECK:
        if name not in tables:
            continue  # table may not be ORM-registered
        table = tables[name]
        if "organization_id" not in table.columns:
            continue
        col = table.columns["organization_id"]
        assert not col.nullable, f"{name}: organization_id must be NOT NULL"
        fk_targets = {fk.target_fullname for fk in col.foreign_keys}
        assert "organizations.id" in fk_targets, f"{name}: missing FK → organizations.id"


def test_every_table_has_server_defaulted_created_at() -> None:
    for name, table in _tables().items():
        if name in _SKIP_CREATED_AT_CHECK:
            continue
        if "created_at" not in table.columns:
            continue  # some tables may not have it — don't enforce universally
        col = table.columns["created_at"]
        assert not col.nullable, f"{name}: created_at must be NOT NULL"
        assert col.server_default is not None, f"{name}: created_at must have server_default"


def test_same_org_composite_fks_present() -> None:
    """INV-TENANT-4 / INV-TABLE-1: cross-org references are structurally banned."""
    tables = _tables()
    composite_fk_names = {
        constraint.name
        for table in tables.values()
        for constraint in table.foreign_key_constraints
        if len(constraint.columns) > 1
    }
    # sessions references member_auth with a composite FK
    assert "fk_sessions_auth_identity_same_org" in composite_fk_names
    # actors parent/created_by same-org
    assert "fk_actors_parent_same_org" in composite_fk_names
    assert "fk_actors_created_by_same_org" in composite_fk_names


def test_membership_identity_fk_is_deliberately_single_column() -> None:
    """Doc 05 §2: an identity MAY hold memberships in multiple organizations."""
    col = _tables()["memberships"].columns["auth_identity_id"]
    # member_auth is the canonical table name (was auth_identities)
    fk_targets = {fk.target_fullname for fk in col.foreign_keys}
    assert any("id" in t and ("auth" in t or "member" in t) for t in fk_targets), (
        f"memberships.auth_identity_id FK target unexpected: {fk_targets}"
    )


def test_auth_identity_uniqueness_rules() -> None:
    # member_auth is the canonical table for auth identities
    table = _tables()["member_auth"]
    unique_sets = {
        tuple(sorted(col.name for col in constraint.columns))
        for constraint in table.constraints
        if isinstance(constraint, UniqueConstraint)
    }
    # There should be at least one unique constraint involving organization_id
    org_unique = [s for s in unique_sets if "organization_id" in s]
    assert org_unique, (
        f"member_auth has no unique constraint involving organization_id. Got: {unique_sets}"
    )


def test_membership_pair_is_unique() -> None:
    table = _tables()["memberships"]
    unique_sets = {
        tuple(sorted(col.name for col in constraint.columns))
        for constraint in table.constraints
        if isinstance(constraint, UniqueConstraint)
    }
    assert ("auth_identity_id", "organization_id") in unique_sets


def test_models_importable_via_package_root() -> None:
    for model in (Organization, Actor, MemberAuth, Membership, Session):
        assert model.__mapper__ is not None
